### ISSUE TITLE
关于html文件热更新

### ISSUE THREAD

**Issue by Kimkow** [pomelott/webpack-multi-page-cli#1]
在修改文件时，html里引入js文件，自改引入的js文件，html会自动更新。但是直接修改html页面时，发现浏览器并不会自动更新，需要手动刷新。这是为什么？求助

**Comment by cjcj5438** [comment]
添加配置:
hotOnly:true 

或者是手动添加文件检测
if(module.hot){
    module.hot.accept('./component/a',function(){
      app.removeChild(list)
     let componentA = require ('./component/a').componentA
     let newList=componentA()
     app.appenChild(newList)
      list=newList
    })
}

或者是使用 vue-loader 之类 它们集成了module hot reloading

**Comment by pomelott** [comment]
html页面不在运行时中，修改html需要手动刷新。开发过程中，html里面我们一般当做入口，代码都是很简洁的。还有就是 2.0 已发布，可以重新尝试下，有问题随时沟通
