### ISSUE TITLE
postcss 一直不起作用

### ISSUE THREAD

**Issue by arieltlm** [pomelott/webpack-multi-page-cli#6]
请问楼主我陪的postcss-loader为何一直不起作用，就是没有添加前缀？安装的是 npm install --save-dev postcss-loader autoprefixer

**Comment by cjcj5438** [comment]
那要看你postcss.config.js 文件是否写正确了.

**Comment by pomelott** [comment]
2.x 版本已经发布， postcss已配置好，可以尝试下。有问题随时再沟通。 @arieltlm  @cjcj5438
